// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt09buDnRv1ub2PqmI46hriGPk-DjfwN8',
    appId: '1:919814100716:web:d675afa8e9cde9885b77c9',
    messagingSenderId: '919814100716',
    projectId: 'wartegtubes',
    authDomain: 'wartegtubes.firebaseapp.com',
    storageBucket: 'wartegtubes.firebasestorage.app',
    measurementId: 'G-0KZ22YCDVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBM54hbJVKylnyFi1bcUG4TpquNbeJzd4',
    appId: '1:919814100716:android:74ecc8d1001adb885b77c9',
    messagingSenderId: '919814100716',
    projectId: 'wartegtubes',
    storageBucket: 'wartegtubes.firebasestorage.app',
  );
}
